# Generated by Django 2.2.5 on 2019-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ship_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='customer',
            name='ship_city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='ship_country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
